language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - npm install

script:
  # TODO: Fix project lint
  #- ng lint
  - npm run build:lib:prod
  - npm run build:docs:prod
