language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli

script:
  # TODO: Fix project lint
  #- ng lint
  - npm run build:lib:prod
  - npm run build:docs:prod
