language: node_js
node_js:
  - "14"
dist: trusty
sudo: required
before_script:
  - npm install -g @angular/cli

jobs:
  include:
    # TODO: Fix ng lint
    #- stage: "Tests"
    #  name: "Angular lint"
    #  script:
    #    - ng lint
    - stage: "Building"
      script:
        - npm run build:lib:prod
        - npm run build:docs:prod
